-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: ../../all/extensions/Wikispeech/sql/abstractSchemaChanges/patch-wikispeech_utterance-wsu_date_stored.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  wikispeech_utterance ALTER wsu_date_stored TYPE TIMESTAMPTZ;
ALTER TABLE  wikispeech_utterance ALTER wsu_date_stored
DROP  DEFAULT;
ALTER TABLE  wikispeech_utterance ALTER wsu_date_stored TYPE TIMESTAMPTZ;