# If you want to use non-default values in your config it's best to use an
# override file rather than to edit this one. See
# https://docs.docker.com/compose/multiple-compose-files/merge/ for details.

version: "3.8"
name: speechoid
services:
  mariadb:
    image: mariadb:10.5.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pronlex
      - MYSQL_USER=pronlex
      - MYSQL_PASSWORD=pronlex

  # Disabled for now, see https://phabricator.wikimedia.org/T384313.
  # ahotts:
  #   image: docker-registry.wikimedia.org/wikimedia/mediawiki-services-wikispeech-ahotts:2021-07-07-080449-production
  #   expose:
  #     - "1200"

  mishkal:
    image: docker-registry.wikimedia.org/wikimedia/mediawiki-services-wikispeech-mishkal:2025-01-21-125334-production
    expose:
      - "8080"
    entrypoint: ./interfaces/web/mishkal-webserver.py

  mary-tts:
    image: docker-registry.wikimedia.org/wikimedia/mediawiki-services-wikispeech-mary-tts:2024-02-28-153902-production
    environment:
      - MARY_TTS_MISHKAL_URL=http://mishkal:8080/
      - HAPROXY_MARY_TTS_BACKEND_MAXIMUM_CONCURRENT_CONNECTIONS=4
      # - HAPROXY_QUEUE_SIZE=100
      # - HAPROXY_TIMEOUT_CONNECT=60s
      # - HAPROXY_TIMEOUT_CLIENT=60s
      # - HAPROXY_TIMEOUT_SERVER=60s
      # - HAPROXY_MARY_TTS_FRONTEND_PORT=8080
      # - HAPROXY_MARY_TTS_BACKEND_PORT=59125
      # - HAPROXY_STATS_FRONTEND_REFRESH_RATE=4s
    expose:
      - "8080"
    volumes:
      - ./compose-files/wait-for-it.sh:/srv/compose/wait-for-it.sh
      - ./compose-files/mary-entrypoint.sh:/srv/compose/entrypoint.sh
    entrypoint: /srv/compose/entrypoint.sh

  symbolset:
    image: docker-registry.wikimedia.org/wikimedia/mediawiki-services-wikispeech-symbolset:2024-02-28-153900-production
    expose:
      - "8771"
    ports:
      - 8771:8771

  pronlex:
    image: docker-registry.wikimedia.org/wikimedia/mediawiki-services-wikispeech-pronlex:2024-02-28-153924-production
    expose:
      - "8787"
    # environment:
    # If this is set, Pronlex will connect to this MariaDB database.
    # If this NOT is set, Pronlex will use built in SQLite database.
    # - PRONLEX_MARIADB_URI=speechoid:password@tcp(wikispeech-tts-pronlex:3306)
    volumes:
      - ./compose-files/wait-for-it.sh:/srv/compose/wait-for-it.sh
      - ./compose-files/pronlex-entrypoint.sh:/srv/compose/entrypoint.sh
    entrypoint: /srv/compose/entrypoint.sh

  # This is a temporary workaround to handle low volume samples from MaryTTS.
  sox-proxy:
    image: docker-registry.wikimedia.org/repos/mediawiki/services/speechoid/sox-proxy:2024-03-18-production
    expose:
      - "5000"
    ports:
      - 5000:5000
    environment:
      - SPEECHOID_URL=http://wikispeech-server:10001/

  wikispeech-server:
    image: docker-registry.wikimedia.org/wikimedia/mediawiki-services-wikispeech-wikispeech-server:2024-02-28-153857-production
    expose:
      - "10001"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - ./compose-files/wikispeech-server-entrypoint.sh:/srv/compose/entrypoint.sh
      - ./compose-files/wikispeech-server.conf:/srv/wikispeech-server/wikispeech_server/default.conf
      - ./compose-files/wait-for-it.sh:/srv/compose/wait-for-it.sh
    entrypoint: /srv/compose/entrypoint.sh
    environment:
      - HAPROXY_QUEUE_SIZE=100
      - HAPROXY_WIKISPEECH_SERVER_BACKEND_MAXIMUM_CONCURRENT_CONNECTIONS=1
      - HAPROXY_TIMEOUT_CONNECT=60s
      - HAPROXY_TIMEOUT_CLIENT=60s
      - HAPROXY_TIMEOUT_SERVER=60s
      - HAPROXY_WIKISPEECH_SERVER_BACKEND_PORT=10000
      - HAPROXY_WIKISPEECH_SERVER_FRONTEND_PORT=10001
      - HAPROXY_STATS_FRONTEND_PORT=10002
      - HAPROXY_STATS_FRONTEND_REFRESH_RATE=4s
