-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-wikispeech_utterance-wsu_message_key.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/wikispeech_utterance
  ADD COLUMN wsu_message_key VARCHAR(255) DEFAULT NULL;
