-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikispeech/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikispeech_utterance (
  wsu_utterance_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wsu_page_id INT UNSIGNED NOT NULL,
  wsu_lang VARBINARY(35) NOT NULL,
  wsu_seg_hash CHAR(64) NOT NULL,
  wsu_voice VARCHAR(30) NOT NULL,
  wsu_date_stored BINARY(14) NOT NULL,
  INDEX get_utterance (
    wsu_page_id, wsu_lang, wsu_voice,
    wsu_seg_hash
  ),
  INDEX expire_page_utterances (wsu_page_id),
  INDEX expire_utterances_lang (wsu_lang),
  INDEX expire_utterances_lang_voice (wsu_lang, wsu_voice),
  INDEX expire_utterances_ttl (wsu_date_stored),
  PRIMARY KEY(wsu_utterance_id)
) /*$wgDBTableOptions*/;
